spring:
  application:
    name: Demo
  datasource:
    url: jdbc:mariadb://alp-backend.viriyah.cloud:3306/vapi
    username: alp
    password: alp@2021
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect

server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /demo

management:
  metrics:
    enable:
      all: false
      demo: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health,prometheus
      path-mapping:
        health: /health
        info: /info
        prometheus: /metrics